spring:
  application:
    name: Identity Service

  profiles:
    active:
      - ${APP_PROFILE:dev}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  duration: ${JWT_DURATION}
  private-key: ${JWT_PRIVATE_KEY}
  public-key: ${JWT_PUBLIC_KEY}

cors:
  origins: ${CORS_ORIGINS}

server:
  port: ${SERVER_PORT:8080}